//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;
using DevExpress.Persistent.Base;
using GRPS_BLAZOR.Module.Interfaces;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{
    //[NavigationItem("Grips Desktop")]
    [VisibleInReports]
    public partial class BOMItem : CustomBaseClass
    {
        decimal fQuantity;
        public decimal Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<decimal>(nameof(Quantity), ref fQuantity, value); }
        }
        EnumInstance fSource;
        [Association(@"BOMItemReferencesEnumInstance")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        Period fActiveFrom;
        [Association(@"BOMItemReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"BOMItemReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        BOM fBOM;
        [Association(@"BOMItemReferencesBOM")]
        public BOM BOM
        {
            get { return fBOM; }
            set { SetPropertyValue<BOM>(nameof(BOM), ref fBOM, value); }
        }
        Part fPart;
        [Association(@"BOMItemReferencesPart")]
        public Part Part
        {
            get { return fPart; }
            set { SetPropertyValue<Part>(nameof(Part), ref fPart, value); }
        }

        Company fCompany;
        [Association(@"BOMItemReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
    }

}
