//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class BOMInserter : XPCustomObject
    {
        int fOID;
        public int OID
        {
            get { return fOID; }
            set { SetPropertyValue<int>(nameof(OID), ref fOID, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fProduct;
        public int Product
        {
            get { return fProduct; }
            set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
        }
        int fProductWeight;
        public int ProductWeight
        {
            get { return fProductWeight; }
            set { SetPropertyValue<int>(nameof(ProductWeight), ref fProductWeight, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        string fAssemblyCode;
        public string AssemblyCode
        {
            get { return fAssemblyCode; }
            set { SetPropertyValue<string>(nameof(AssemblyCode), ref fAssemblyCode, value); }
        }
        bool fIsAssembly;
        public bool IsAssembly
        {
            get { return fIsAssembly; }
            set { SetPropertyValue<bool>(nameof(IsAssembly), ref fIsAssembly, value); }
        }
    }

}
