//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{
    [NavigationItem("Grips Desktop")]

    public partial class ComplianceRule : CustomBaseClass
    {
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        Period fActiveFrom;
        [Association(@"ComplianceRuleReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"ComplianceRuleReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }

        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTemplateName;
        public string TemplateName
        {
            get { return fTemplateName; }
            set { SetPropertyValue<string>(nameof(TemplateName), ref fTemplateName, value); }
        }
        bool fIsTemplate;
        public bool IsTemplate
        {
            get { return fIsTemplate; }
            set { SetPropertyValue<bool>(nameof(IsTemplate), ref fIsTemplate, value); }
        }
        Company fCompany;
        [Association(@"ComplianceRuleReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        [Association(@"AustriaReturnCellReferencesComplianceRule")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells)); } }
        [Association(@"CanadaReturnCellReferencesComplianceRule")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells)); } }
        [Association(@"IDASPackTotalReferencesComplianceRule")]
        public XPCollection<IDASPackTotal> IDASPackTotals { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals)); } }
        [Association(@"IDASReturnCellReferencesComplianceRule")]
        public XPCollection<IDASReturnCell> IDASReturnCells { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells)); } }
        [Association(@"RepakReturnCellReferencesComplianceRule")]
        public XPCollection<RepakReturnCell> RepakReturnCells { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells)); } }

        [Browsable(false)]  //TODO: This relationship should be removed, it's no longer necessary
        [Association(@"RuleItemReferencesComplianceRule")]
        public XPCollection<RuleItem> RuleItems { get { return GetCollection<RuleItem>(nameof(RuleItems)); } }

        [Association(@"SalesVolumeReferencesComplianceRule")]
        public XPCollection<SalesVolume> SalesVolumes { get { return GetCollection<SalesVolume>(nameof(SalesVolumes)); } }
        [Association(@"TotalPackWeightReferencesComplianceRule")]
        public XPCollection<TotalPackWeight> TotalPackWeights { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights)); } }
        [Association(@"UKReturnCellReferencesComplianceRule")]
        public XPCollection<UKReturnCell> UKReturnCells { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells)); } }
    }

}
