//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using GRPS_BLAZOR.Module.BusinessObjects.Base;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.Model;
using DevExpress.ExpressApp;
using DevExpress.Persistent.BaseImpl;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{
    [NavigationItem("Grips Desktop")]
    [VisibleInReports]
    public partial class Customer : GRIPSObject
    {
        string fPartyCode;
        public string PartyCode
        {
            get { return fPartyCode; }
            set { SetPropertyValue<string>(nameof(PartyCode), ref fPartyCode, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        string fName;
        [RuleRequiredField(DefaultContexts.Save)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        CustomerGroup fGroup;
        [XafDisplayName("Customer Group")]
        [Association(@"CustomerReferencesCustomerGroup")]
        public CustomerGroup Group
        {
            get { return fGroup; }
            set { SetPropertyValue<CustomerGroup>(nameof(Group), ref fGroup, value); }
        }
        EnumInstance fPartyType;
        [XafDisplayName("Customer Type")]
        [DataSourceCriteria("Domain.Name = 'CustomerType'")]
        [Association(@"CustomerReferencesEnumInstance")]
        public EnumInstance PartyType
        {
            get { return fPartyType; }
            set { SetPropertyValue<EnumInstance>(nameof(PartyType), ref fPartyType, value); }
        }
 
        Period fActiveFrom;
        [Association(@"CustomerReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"CustomerReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"CustomerReferencesCompany")]
        [Browsable(false)]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }

        [DevExpress.Xpo.Aggregated]
        [Association(@"CustomerAddressReferencesCustomer")]
        public XPCollection<CustomerAddress> CustomerAddresses { get { return GetCollection<CustomerAddress>(nameof(CustomerAddresses)); } }

        [DevExpress.Xpo.Aggregated]
        [Association(@"CustomerConReferencesCustomer")]
        public XPCollection<CustomerCon> CustomerCons { get { return GetCollection<CustomerCon>(nameof(CustomerCons)); } }

        [Browsable(false)]
        [Association(@"SalesVolumeReferencesCustomer")]
        public XPCollection<SalesVolume> SalesVolumes { get { return GetCollection<SalesVolume>(nameof(SalesVolumes)); } }

        private XPCollection<AuditDataItemPersistent> changeHistory;
        [CollectionOperationSet(AllowAdd = false, AllowRemove = false)]
        public XPCollection<AuditDataItemPersistent> ChangeHistory
        {
            get
            {
                if (changeHistory == null)
                {
                    changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
                }
                return changeHistory;
            }
        }
    }

}
