////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//using System;
//using DevExpress.Xpo;
//using DevExpress.Xpo.Metadata;
//using DevExpress.Data.Filtering;
//using System.Collections.Generic;
//using System.ComponentModel;
//using System.Reflection;
//using GRPS_BLAZOR.Module.BusinessObjects.Base;

//namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
//{

//    public partial class EnumDomainSubset : CustomBaseClass
//    {
//        Period fActiveFrom;
//        [Association(@"EnumDomainSubsetReferencesPeriod")]
//        public Period ActiveFrom
//        {
//            get { return fActiveFrom; }
//            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
//        }
//        Period fActiveTo;
//        [Association(@"EnumDomainSubsetReferencesPeriod1")]
//        public Period ActiveTo
//        {
//            get { return fActiveTo; }
//            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
//        }
//        Company fCompany;
//        [Association(@"EnumDomainSubsetReferencesCompany")]
//        public Company Company
//        {
//            get { return fCompany; }
//            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
//        }
//        string fName;
//        public string Name
//        {
//            get { return fName; }
//            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
//        }
//        EnumDomain fDomain;
//        [Association(@"EnumDomainSubsetReferencesEnumDomain")]
//        public EnumDomain Domain
//        {
//            get { return fDomain; }
//            set { SetPropertyValue<EnumDomain>(nameof(Domain), ref fDomain, value); }
//        }
//        [Association(@"EnumDomSubItemReferencesEnumDomainSubset")]
//        public XPCollection<EnumDomSubItem> EnumDomSubItems { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems)); } }
//    }

//}
