//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class EnumInstance : CustomBaseClass
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        EnumDomain fDomain;
        [Association(@"EnumInstanceReferencesEnumDomain")]
        public EnumDomain Domain
        {
            get { return fDomain; }
            set { SetPropertyValue<EnumDomain>(nameof(Domain), ref fDomain, value); }
        }

        //Period fActiveFrom;
        //[Association(@"EnumInstanceReferencesPeriod")]
        //public Period ActiveFrom
        //{
        //    get { return fActiveFrom; }
        //    set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        //}
        //Period fActiveTo;
        //[Association(@"EnumInstanceReferencesPeriod1")]
        //public Period ActiveTo
        //{
        //    get { return fActiveTo; }
        //    set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        //}
        int fSortId;
        public int SortId
        {
            get { return fSortId; }
            set { SetPropertyValue<int>(nameof(SortId), ref fSortId, value); }
        }
        //Company fCompany;
        //[Association(@"EnumInstanceReferencesCompany")]
        //public Company Company
        //{
        //    get { return fCompany; }
        //    set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        //}
        [Association(@"AustriaReturnCellReferencesEnumInstance")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells)); } }
        [Association(@"AustriaReturnCellReferencesEnumInstance1")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells1 { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells1)); } }
        [Association(@"AustriaReturnCellReferencesEnumInstance2")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells2 { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells2)); } }
        [Association(@"AustriaReturnCellReferencesEnumInstance3")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells3 { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells3)); } }
        [Association(@"AustriaReturnCellReferencesEnumInstance4")]
        public XPCollection<AustriaReturnCell> AustriaReturnCells4 { get { return GetCollection<AustriaReturnCell>(nameof(AustriaReturnCells4)); } }
        [Association(@"BOMItemReferencesEnumInstance")]
        public XPCollection<BOMItem> BOMItems { get { return GetCollection<BOMItem>(nameof(BOMItems)); } }
        [Association(@"CanadaReturnCellReferencesEnumInstance")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells)); } }
        [Association(@"CanadaReturnCellReferencesEnumInstance1")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells1 { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells1)); } }
        [Association(@"CanadaReturnCellReferencesEnumInstance2")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells2 { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells2)); } }
        [Association(@"CanadaReturnCellReferencesEnumInstance3")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells3 { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells3)); } }
        [Association(@"CanadaReturnCellReferencesEnumInstance4")]
        public XPCollection<CanadaReturnCell> CanadaReturnCells4 { get { return GetCollection<CanadaReturnCell>(nameof(CanadaReturnCells4)); } }
        [Association(@"CustomerReferencesEnumInstance")]
        public XPCollection<Customer> Customers { get { return GetCollection<Customer>(nameof(Customers)); } }
        [Association(@"DimensionReferencesEnumInstance")]
        public XPCollection<Dimension> Dimensions { get { return GetCollection<Dimension>(nameof(Dimensions)); } }
        [Association(@"DimensionReferencesEnumInstance1")]
        public XPCollection<Dimension> Dimensions1 { get { return GetCollection<Dimension>(nameof(Dimensions1)); } }
        //[Association(@"EnumDomSubItemReferencesEnumInstance")]
        //public XPCollection<EnumDomSubItem> EnumDomSubItems { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems)); } }
        [Association(@"FactSUPItemsReferencesEnumInstance")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection)); } }
        [Association(@"FactSUPItemsReferencesEnumInstance1")]
        public XPCollection<FactSUPItems> FactSUPItemsCollection1 { get { return GetCollection<FactSUPItems>(nameof(FactSUPItemsCollection1)); } }
        [Association(@"IDASPackTotalReferencesEnumInstance")]
        public XPCollection<IDASPackTotal> IDASPackTotals { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals)); } }
        [Association(@"IDASPackTotalReferencesEnumInstance1")]
        public XPCollection<IDASPackTotal> IDASPackTotals1 { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals1)); } }
        [Association(@"IDASPackTotalReferencesEnumInstance2")]
        public XPCollection<IDASPackTotal> IDASPackTotals2 { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals2)); } }
        [Association(@"IDASPackTotalReferencesEnumInstance3")]
        public XPCollection<IDASPackTotal> IDASPackTotals3 { get { return GetCollection<IDASPackTotal>(nameof(IDASPackTotals3)); } }
        [Association(@"IDASReturnCellReferencesEnumInstance")]
        public XPCollection<IDASReturnCell> IDASReturnCells { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells)); } }
        [Association(@"IDASReturnCellReferencesEnumInstance1")]
        public XPCollection<IDASReturnCell> IDASReturnCells1 { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells1)); } }
        [Association(@"IDASReturnCellReferencesEnumInstance2")]
        public XPCollection<IDASReturnCell> IDASReturnCells2 { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells2)); } }
        [Association(@"IDASReturnCellReferencesEnumInstance3")]
        public XPCollection<IDASReturnCell> IDASReturnCells3 { get { return GetCollection<IDASReturnCell>(nameof(IDASReturnCells3)); } }
        [Association(@"KPIDEFReferencesEnumInstance")]
        public XPCollection<KPIDEF> KPIDEFs { get { return GetCollection<KPIDEF>(nameof(KPIDEFs)); } }
        [Association(@"MaterialMappingReferencesEnumInstance")]
        public XPCollection<MaterialMapping> MaterialMappings { get { return GetCollection<MaterialMapping>(nameof(MaterialMappings)); } }
        [Association(@"MaterialMappingReferencesEnumInstance1")]
        public XPCollection<MaterialMapping> MaterialMappings1 { get { return GetCollection<MaterialMapping>(nameof(MaterialMappings1)); } }
        [Association(@"PackagingWeightReferencesEnumInstance")]
        public XPCollection<PackagingWeight> PackagingWeights { get { return GetCollection<PackagingWeight>(nameof(PackagingWeights)); } }
        [Association(@"PackagingWeightReferencesEnumInstance1")]
        public XPCollection<PackagingWeight> PackagingWeights1 { get { return GetCollection<PackagingWeight>(nameof(PackagingWeights1)); } }
        [Association(@"PackWeightReferencesEnumInstance")]
        public XPCollection<PackWeight> PackWeights { get { return GetCollection<PackWeight>(nameof(PackWeights)); } }
        [Association(@"PackWeightReferencesEnumInstance1")]
        public XPCollection<PackWeight> PackWeights1 { get { return GetCollection<PackWeight>(nameof(PackWeights1)); } }
        [Association(@"PackWeightReferencesEnumInstance2")]
        public XPCollection<PackWeight> PackWeights2 { get { return GetCollection<PackWeight>(nameof(PackWeights2)); } }
        [Association(@"PackWeightReferencesEnumInstance3")]
        public XPCollection<PackWeight> PackWeights3 { get { return GetCollection<PackWeight>(nameof(PackWeights3)); } }
        [Association(@"PartReferencesEnumInstance")]
        public XPCollection<Part> Parts { get { return GetCollection<Part>(nameof(Parts)); } }
        [Association(@"ProdWeightReferencesEnumInstance")]
        public XPCollection<ProdWeight> ProdWeights { get { return GetCollection<ProdWeight>(nameof(ProdWeights)); } }
        [Association(@"ProdWeightReferencesEnumInstance1")]
        public XPCollection<ProdWeight> ProdWeights1 { get { return GetCollection<ProdWeight>(nameof(ProdWeights1)); } }
        [Association(@"RepakReturnCellReferencesEnumInstance")]
        public XPCollection<RepakReturnCell> RepakReturnCells { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells)); } }
        [Association(@"RepakReturnCellReferencesEnumInstance1")]
        public XPCollection<RepakReturnCell> RepakReturnCells1 { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells1)); } }
        [Association(@"RepakReturnCellReferencesEnumInstance2")]
        public XPCollection<RepakReturnCell> RepakReturnCells2 { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells2)); } }
        [Association(@"RepakReturnCellReferencesEnumInstance3")]
        public XPCollection<RepakReturnCell> RepakReturnCells3 { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells3)); } }
        [Association(@"RepakReturnCellReferencesEnumInstance4")]
        public XPCollection<RepakReturnCell> RepakReturnCells4 { get { return GetCollection<RepakReturnCell>(nameof(RepakReturnCells4)); } }
        [Association(@"SampleCoefficientReferencesEnumInstance")]
        public XPCollection<SampleCoefficient> SampleCoefficients { get { return GetCollection<SampleCoefficient>(nameof(SampleCoefficients)); } }
        [Association(@"SampleCoefficientReferencesEnumInstance1")]
        public XPCollection<SampleCoefficient> SampleCoefficients1 { get { return GetCollection<SampleCoefficient>(nameof(SampleCoefficients1)); } }
        [Association(@"SampleCoefficientReferencesEnumInstance2")]
        public XPCollection<SampleCoefficient> SampleCoefficients2 { get { return GetCollection<SampleCoefficient>(nameof(SampleCoefficients2)); } }
        [Association(@"SampleCoefficientReferencesEnumInstance3")]
        public XPCollection<SampleCoefficient> SampleCoefficients3 { get { return GetCollection<SampleCoefficient>(nameof(SampleCoefficients3)); } }
        [Association(@"SamplePackWeightReferencesEnumInstance")]
        public XPCollection<SamplePackWeight> SamplePackWeights { get { return GetCollection<SamplePackWeight>(nameof(SamplePackWeights)); } }
        [Association(@"SamplePackWeightReferencesEnumInstance1")]
        public XPCollection<SamplePackWeight> SamplePackWeights1 { get { return GetCollection<SamplePackWeight>(nameof(SamplePackWeights1)); } }
        [Association(@"SamplePackWeightReferencesEnumInstance2")]
        public XPCollection<SamplePackWeight> SamplePackWeights2 { get { return GetCollection<SamplePackWeight>(nameof(SamplePackWeights2)); } }
        [Association(@"SamplePackWeightReferencesEnumInstance3")]
        public XPCollection<SamplePackWeight> SamplePackWeights3 { get { return GetCollection<SamplePackWeight>(nameof(SamplePackWeights3)); } }
        [Association(@"SRAttributeReferencesEnumInstance")]
        public XPCollection<SRAttribute> SRAttributes { get { return GetCollection<SRAttribute>(nameof(SRAttributes)); } }
        [Association(@"SRAttributeReferencesEnumInstance1")]
        public XPCollection<SRAttribute> SRAttributes1 { get { return GetCollection<SRAttribute>(nameof(SRAttributes1)); } }
        [Association(@"SupplierReferencesEnumInstance")]
        public XPCollection<Supplier> Suppliers { get { return GetCollection<Supplier>(nameof(Suppliers)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance")]
        public XPCollection<TotalPackWeight> TotalPackWeights { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance1")]
        public XPCollection<TotalPackWeight> TotalPackWeights1 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights1)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance2")]
        public XPCollection<TotalPackWeight> TotalPackWeights2 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights2)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance3")]
        public XPCollection<TotalPackWeight> TotalPackWeights3 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights3)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance4")]
        public XPCollection<TotalPackWeight> TotalPackWeights4 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights4)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance5")]
        public XPCollection<TotalPackWeight> TotalPackWeights5 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights5)); } }
        [Association(@"TotalPackWeightReferencesEnumInstance6")]
        public XPCollection<TotalPackWeight> TotalPackWeights6 { get { return GetCollection<TotalPackWeight>(nameof(TotalPackWeights6)); } }
        [Association(@"UKReturnCellReferencesEnumInstance")]
        public XPCollection<UKReturnCell> UKReturnCells { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells)); } }
        [Association(@"UKReturnCellReferencesEnumInstance1")]
        public XPCollection<UKReturnCell> UKReturnCells1 { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells1)); } }
        [Association(@"UKReturnCellReferencesEnumInstance2")]
        public XPCollection<UKReturnCell> UKReturnCells2 { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells2)); } }
        [Association(@"UKReturnCellReferencesEnumInstance3")]
        public XPCollection<UKReturnCell> UKReturnCells3 { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells3)); } }
        [Association(@"UKReturnCellReferencesEnumInstance4")]
        public XPCollection<UKReturnCell> UKReturnCells4 { get { return GetCollection<UKReturnCell>(nameof(UKReturnCells4)); } }
    }

}
