//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class EnumDomain : CustomBaseClass
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }

        //Period fActiveFrom;
        //[Association(@"EnumDomainReferencesPeriod")]
        //public Period ActiveFrom
        //{
        //    get { return fActiveFrom; }
        //    set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        //}
        //Period fActiveTo;
        //[Association(@"EnumDomainReferencesPeriod1")]
        //public Period ActiveTo
        //{
        //    get { return fActiveTo; }
        //    set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        //}
        //Company fCompany;
        //[Association(@"EnumDomainReferencesCompany")]
        //public Company Company
        //{
        //    get { return fCompany; }
        //    set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        //}

        EnumDomain parent;
        [Association("EnumDomain-Subdomain")]
        public EnumDomain Parent
        {
            get => parent;
            set => SetPropertyValue(nameof(Parent), ref parent, value);
        }

        [Association("EnumDomain-Subdomain")]
        public XPCollection<EnumDomain> Subdomains
        {
            get
            {
                return GetCollection<EnumDomain>(nameof(Subdomains));
            }
        }

        //[Association(@"EnumDomainSubsetReferencesEnumDomain")]
        //public XPCollection<EnumDomainSubset> EnumDomainSubsets { get { return GetCollection<EnumDomainSubset>(nameof(EnumDomainSubsets)); } }
        //[Association(@"EnumDomSubItemReferencesEnumDomain")]
        //public XPCollection<EnumDomSubItem> EnumDomSubItems { get { return GetCollection<EnumDomSubItem>(nameof(EnumDomSubItems)); } }
        [Association(@"EnumInstanceReferencesEnumDomain")]
        public XPCollection<EnumInstance> EnumInstances { get { return GetCollection<EnumInstance>(nameof(EnumInstances)); } }
    }

}
