//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class FactSUPItemsInserter : XPCustomObject
    {
        int fOID;
        public int OID
        {
            get { return fOID; }
            set { SetPropertyValue<int>(nameof(OID), ref fOID, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        int fProduct;
        public int Product
        {
            get { return fProduct; }
            set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
        }
        int fCustomer;
        public int Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<int>(nameof(Customer), ref fCustomer, value); }
        }
        int fSource;
        public int Source
        {
            get { return fSource; }
            set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
        }
        int fDestination;
        public int Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<int>(nameof(Destination), ref fDestination, value); }
        }
        int fMaterialType;
        public int MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<int>(nameof(MaterialType), ref fMaterialType, value); }
        }
        int fItemType;
        public int ItemType
        {
            get { return fItemType; }
            set { SetPropertyValue<int>(nameof(ItemType), ref fItemType, value); }
        }
        double fTotalQuantity;
        public double TotalQuantity
        {
            get { return fTotalQuantity; }
            set { SetPropertyValue<double>(nameof(TotalQuantity), ref fTotalQuantity, value); }
        }
        DateTime fCalcDate;
        public DateTime CalcDate
        {
            get { return fCalcDate; }
            set { SetPropertyValue<DateTime>(nameof(CalcDate), ref fCalcDate, value); }
        }
    }

}
