//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class FactSales : XPLiteObject
    {
        int fProduct;
        public int Product
        {
            get { return fProduct; }
            set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        decimal fCases;
        public decimal Cases
        {
            get { return fCases; }
            set { SetPropertyValue<decimal>(nameof(Cases), ref fCases, value); }
        }
        decimal fWeightKgs;
        public decimal WeightKgs
        {
            get { return fWeightKgs; }
            set { SetPropertyValue<decimal>(nameof(WeightKgs), ref fWeightKgs, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        DateTime fCalcDate;
        public DateTime CalcDate
        {
            get { return fCalcDate; }
            set { SetPropertyValue<DateTime>(nameof(CalcDate), ref fCalcDate, value); }
        }
        int fCustomer;
        public int Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<int>(nameof(Customer), ref fCustomer, value); }
        }
    }

}
