//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class FactPrimaryEndOfLife : CustomBaseClass
    {
        Period fActiveFrom;
        [Association(@"FactPrimaryEndOfLifeReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"FactPrimaryEndOfLifeReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"FactPrimaryEndOfLifeReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        DimProduct fProduct;
        [Association(@"FactPrimaryEndOfLifeReferencesDimProduct")]
        public DimProduct Product
        {
            get { return fProduct; }
            set { SetPropertyValue<DimProduct>(nameof(Product), ref fProduct, value); }
        }
        double fRecyclabilityPercent;
        public double RecyclabilityPercent
        {
            get { return fRecyclabilityPercent; }
            set { SetPropertyValue<double>(nameof(RecyclabilityPercent), ref fRecyclabilityPercent, value); }
        }
        double fReusabilityPercent;
        public double ReusabilityPercent
        {
            get { return fReusabilityPercent; }
            set { SetPropertyValue<double>(nameof(ReusabilityPercent), ref fReusabilityPercent, value); }
        }
        double fCompostabilityPercent;
        public double CompostabilityPercent
        {
            get { return fCompostabilityPercent; }
            set { SetPropertyValue<double>(nameof(CompostabilityPercent), ref fCompostabilityPercent, value); }
        }
        int fTotalPercent;
        public int TotalPercent
        {
            get { return fTotalPercent; }
            set { SetPropertyValue<int>(nameof(TotalPercent), ref fTotalPercent, value); }
        }
        double fNonRecyclabilityPercent;
        public double NonRecyclabilityPercent
        {
            get { return fNonRecyclabilityPercent; }
            set { SetPropertyValue<double>(nameof(NonRecyclabilityPercent), ref fNonRecyclabilityPercent, value); }
        }
    }

}
