//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class IDASPackTotal : CustomBaseClass
    {
        Period fActiveFrom;
        [Association(@"IDASPackTotalReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"IDASPackTotalReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        EnumInstance fSource;
        [Association(@"IDASPackTotalReferencesEnumInstance3")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        EnumInstance fDestination;
        [Association(@"IDASPackTotalReferencesEnumInstance")]
        public EnumInstance Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<EnumInstance>(nameof(Destination), ref fDestination, value); }
        }
        EnumInstance fMaterialType;
        [Association(@"IDASPackTotalReferencesEnumInstance1")]
        public EnumInstance MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialType), ref fMaterialType, value); }
        }
        EnumInstance fPackType;
        [Association(@"IDASPackTotalReferencesEnumInstance2")]
        public EnumInstance PackType
        {
            get { return fPackType; }
            set { SetPropertyValue<EnumInstance>(nameof(PackType), ref fPackType, value); }
        }
        ComplianceRule fCompRule;
        [Association(@"IDASPackTotalReferencesComplianceRule")]
        public ComplianceRule CompRule
        {
            get { return fCompRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(CompRule), ref fCompRule, value); }
        }
        double fPackTonnes;
        public double PackTonnes
        {
            get { return fPackTonnes; }
            set { SetPropertyValue<double>(nameof(PackTonnes), ref fPackTonnes, value); }
        }
        double fProdTonnes;
        public double ProdTonnes
        {
            get { return fProdTonnes; }
            set { SetPropertyValue<double>(nameof(ProdTonnes), ref fProdTonnes, value); }
        }
    }

}
