//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class MaterialMapping : CustomBaseClass
    {
        Period fActiveFrom;
        [Association(@"MaterialMappingReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"MaterialMappingReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"MaterialMappingReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        string fSchemeName;
        public string SchemeName
        {
            get { return fSchemeName; }
            set { SetPropertyValue<string>(nameof(SchemeName), ref fSchemeName, value); }
        }
        int fSortId;
        public int SortId
        {
            get { return fSortId; }
            set { SetPropertyValue<int>(nameof(SortId), ref fSortId, value); }
        }
        EnumInstance fMaterial;
        [Association(@"MaterialMappingReferencesEnumInstance")]
        public EnumInstance Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<EnumInstance>(nameof(Material), ref fMaterial, value); }
        }
        EnumInstance fMaterialCategory;
        [Association(@"MaterialMappingReferencesEnumInstance1")]
        public EnumInstance MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
    }

}
