//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class ProductInserter : XPCustomObject
    {
        int fOID;
        public int OID
        {
            get { return fOID; }
            set { SetPropertyValue<int>(nameof(OID), ref fOID, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fSupplierProdCode;
        public string SupplierProdCode
        {
            get { return fSupplierProdCode; }
            set { SetPropertyValue<string>(nameof(SupplierProdCode), ref fSupplierProdCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        int fUnitType;
        public int UnitType
        {
            get { return fUnitType; }
            set { SetPropertyValue<int>(nameof(UnitType), ref fUnitType, value); }
        }
        string fEANCode;
        public string EANCode
        {
            get { return fEANCode; }
            set { SetPropertyValue<string>(nameof(EANCode), ref fEANCode, value); }
        }
        string fTUCCode;
        public string TUCCode
        {
            get { return fTUCCode; }
            set { SetPropertyValue<string>(nameof(TUCCode), ref fTUCCode, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>(nameof(IsActive), ref fIsActive, value); }
        }
        bool fIsImport;
        public bool IsImport
        {
            get { return fIsImport; }
            set { SetPropertyValue<bool>(nameof(IsImport), ref fIsImport, value); }
        }
        int fSupplier;
        public int Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<int>(nameof(Supplier), ref fSupplier, value); }
        }
        int fActiveBOM;
        public int ActiveBOM
        {
            get { return fActiveBOM; }
            set { SetPropertyValue<int>(nameof(ActiveBOM), ref fActiveBOM, value); }
        }
        int fGroup;
        public int Group
        {
            get { return fGroup; }
            set { SetPropertyValue<int>(nameof(Group), ref fGroup, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        string fOwnBrandName;
        public string OwnBrandName
        {
            get { return fOwnBrandName; }
            set { SetPropertyValue<string>(nameof(OwnBrandName), ref fOwnBrandName, value); }
        }
    }

}
