//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class SalesViewObject : XPCustomObject
    {
        int foid;
        public int oid
        {
            get { return foid; }
            set { SetPropertyValue<int>(nameof(oid), ref foid, value); }
        }
        DateTime fCreatedOn;
        public DateTime CreatedOn
        {
            get { return fCreatedOn; }
            set { SetPropertyValue<DateTime>(nameof(CreatedOn), ref fCreatedOn, value); }
        }
        DateTime fLastChangedOn;
        public DateTime LastChangedOn
        {
            get { return fLastChangedOn; }
            set { SetPropertyValue<DateTime>(nameof(LastChangedOn), ref fLastChangedOn, value); }
        }
        int fCreatedBy;
        public int CreatedBy
        {
            get { return fCreatedBy; }
            set { SetPropertyValue<int>(nameof(CreatedBy), ref fCreatedBy, value); }
        }
        int fLastChangedBy;
        public int LastChangedBy
        {
            get { return fLastChangedBy; }
            set { SetPropertyValue<int>(nameof(LastChangedBy), ref fLastChangedBy, value); }
        }
        int fActiveFrom;
        public int ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<int>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        int fActiveTo;
        public int ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<int>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        decimal fVolume;
        public decimal Volume
        {
            get { return fVolume; }
            set { SetPropertyValue<decimal>(nameof(Volume), ref fVolume, value); }
        }
        int fVolumeType;
        public int VolumeType
        {
            get { return fVolumeType; }
            set { SetPropertyValue<int>(nameof(VolumeType), ref fVolumeType, value); }
        }
        int fGroupId;
        public int GroupId
        {
            get { return fGroupId; }
            set { SetPropertyValue<int>(nameof(GroupId), ref fGroupId, value); }
        }
        int fProduct;
        public int Product
        {
            get { return fProduct; }
            set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
        }
        int fRule;
        public int Rule
        {
            get { return fRule; }
            set { SetPropertyValue<int>(nameof(Rule), ref fRule, value); }
        }
        int fCustomer;
        public int Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<int>(nameof(Customer), ref fCustomer, value); }
        }
        int fBOM;
        public int BOM
        {
            get { return fBOM; }
            set { SetPropertyValue<int>(nameof(BOM), ref fBOM, value); }
        }
        decimal fValue;
        public decimal Value
        {
            get { return fValue; }
            set { SetPropertyValue<decimal>(nameof(Value), ref fValue, value); }
        }
        int fCompany;
        public int Company
        {
            get { return fCompany; }
            set { SetPropertyValue<int>(nameof(Company), ref fCompany, value); }
        }
        int fHasBOM;
        public int HasBOM
        {
            get { return fHasBOM; }
            set { SetPropertyValue<int>(nameof(HasBOM), ref fHasBOM, value); }
        }
        decimal fHasSpecQty;
        public decimal HasSpecQty
        {
            get { return fHasSpecQty; }
            set { SetPropertyValue<decimal>(nameof(HasSpecQty), ref fHasSpecQty, value); }
        }
    }

}
