//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;
using DisplayNameAttribute = System.ComponentModel.DisplayNameAttribute;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class SRAttribute : CustomBaseClass
    {
        Period fActiveFrom;
        [Association(@"SRAttributeReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"SRAttributeReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"SRAttributeReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
        string fAttributeText;
        [DisplayName("Attribute Text Value")]
        public string AttributeText
        {
            get { return fAttributeText; }
            set { SetPropertyValue<string>(nameof(AttributeText), ref fAttributeText, value); }
        }
        double fAttributeNum;
        [DisplayName("Attribute Num Value")]
        public double AttributeNum
        {
            get { return fAttributeNum; }
            set { SetPropertyValue<double>(nameof(AttributeNum), ref fAttributeNum, value); }
        }
        EnumInstance fReportType;
        [Association(@"SRAttributeReferencesEnumInstance1")]
        [DisplayName("Report Name")]
        public EnumInstance ReportType
        {
            get { return fReportType; }
            set { SetPropertyValue<EnumInstance>(nameof(ReportType), ref fReportType, value); }
        }
        EnumInstance fAttributeName;
        [Association(@"SRAttributeReferencesEnumInstance")]
        public EnumInstance AttributeName
        {
            get { return fAttributeName; }
            set { SetPropertyValue<EnumInstance>(nameof(AttributeName), ref fAttributeName, value); }
        }
        Part fComponent;
        [Association(@"SRAttributeReferencesPart")]
        public Part Component
        {
            get { return fComponent; }
            set { SetPropertyValue<Part>(nameof(Component), ref fComponent, value); }
        }
    }

}
