//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using GRPS_BLAZOR.Module.BusinessObjects.Base;

namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    public partial class UKReturnCell : CustomBaseClass
    {
        string fTargetCell;
        public string TargetCell
        {
            get { return fTargetCell; }
            set { SetPropertyValue<string>(nameof(TargetCell), ref fTargetCell, value); }
        }
        EnumInstance fMaterialType;
        [Association(@"UKReturnCellReferencesEnumInstance2")]
        public EnumInstance MaterialType
        {
            get { return fMaterialType; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialType), ref fMaterialType, value); }
        }
        EnumInstance fPackagingType;
        [Association(@"UKReturnCellReferencesEnumInstance3")]
        public EnumInstance PackagingType
        {
            get { return fPackagingType; }
            set { SetPropertyValue<EnumInstance>(nameof(PackagingType), ref fPackagingType, value); }
        }
        EnumInstance fSource;
        [Association(@"UKReturnCellReferencesEnumInstance4")]
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        EnumInstance fDestination;
        [Association(@"UKReturnCellReferencesEnumInstance")]
        public EnumInstance Destination
        {
            get { return fDestination; }
            set { SetPropertyValue<EnumInstance>(nameof(Destination), ref fDestination, value); }
        }
        double fAllocation;
        public double Allocation
        {
            get { return fAllocation; }
            set { SetPropertyValue<double>(nameof(Allocation), ref fAllocation, value); }
        }
        ComplianceRule fRule;
        [Association(@"UKReturnCellReferencesComplianceRule")]
        public ComplianceRule Rule
        {
            get { return fRule; }
            set { SetPropertyValue<ComplianceRule>(nameof(Rule), ref fRule, value); }
        }
        UKReturnLine fParentLine;
        [Association(@"UKReturnCellReferencesUKReturnLine")]
        public UKReturnLine ParentLine
        {
            get { return fParentLine; }
            set { SetPropertyValue<UKReturnLine>(nameof(ParentLine), ref fParentLine, value); }
        }
        EnumInstance fMaterialCategory;
        [Association(@"UKReturnCellReferencesEnumInstance1")]
        public EnumInstance MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }

        Period fActiveFrom;
        [Association(@"UKReturnCellReferencesPeriod")]
        public Period ActiveFrom
        {
            get { return fActiveFrom; }
            set { SetPropertyValue<Period>(nameof(ActiveFrom), ref fActiveFrom, value); }
        }
        Period fActiveTo;
        [Association(@"UKReturnCellReferencesPeriod1")]
        public Period ActiveTo
        {
            get { return fActiveTo; }
            set { SetPropertyValue<Period>(nameof(ActiveTo), ref fActiveTo, value); }
        }
        Company fCompany;
        [Association(@"UKReturnCellReferencesCompany")]
        public Company Company
        {
            get { return fCompany; }
            set { SetPropertyValue<Company>(nameof(Company), ref fCompany, value); }
        }
    }

}
