//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class vwCustomerSales : XPLiteObject
    {
        int fperiod;
        public int period
        {
            get { return fperiod; }
            set { SetPropertyValue<int>(nameof(period), ref fperiod, value); }
        }
        int fcustomerid;
        public int customerid
        {
            get { return fcustomerid; }
            set { SetPropertyValue<int>(nameof(customerid), ref fcustomerid, value); }
        }
        string fcustomername;
        public string customername
        {
            get { return fcustomername; }
            set { SetPropertyValue<string>(nameof(customername), ref fcustomername, value); }
        }
        string fprodcode;
        public string prodcode
        {
            get { return fprodcode; }
            set { SetPropertyValue<string>(nameof(prodcode), ref fprodcode, value); }
        }
        string fprodname;
        public string prodname
        {
            get { return fprodname; }
            set { SetPropertyValue<string>(nameof(prodname), ref fprodname, value); }
        }
        string fproddesc;
        public string proddesc
        {
            get { return fproddesc; }
            set { SetPropertyValue<string>(nameof(proddesc), ref fproddesc, value); }
        }
        int fsaleid;
        public int saleid
        {
            get { return fsaleid; }
            set { SetPropertyValue<int>(nameof(saleid), ref fsaleid, value); }
        }
        int fbomitmid;
        public int bomitmid
        {
            get { return fbomitmid; }
            set { SetPropertyValue<int>(nameof(bomitmid), ref fbomitmid, value); }
        }
        int fpartid;
        public int partid
        {
            get { return fpartid; }
            set { SetPropertyValue<int>(nameof(partid), ref fpartid, value); }
        }
        int fweightid;
        public int weightid
        {
            get { return fweightid; }
            set { SetPropertyValue<int>(nameof(weightid), ref fweightid, value); }
        }
        int fsource;
        public int source
        {
            get { return fsource; }
            set { SetPropertyValue<int>(nameof(source), ref fsource, value); }
        }
        int fdestination;
        public int destination
        {
            get { return fdestination; }
            set { SetPropertyValue<int>(nameof(destination), ref fdestination, value); }
        }
        int fmaterial;
        public int material
        {
            get { return fmaterial; }
            set { SetPropertyValue<int>(nameof(material), ref fmaterial, value); }
        }
        int fpacktype;
        public int packtype
        {
            get { return fpacktype; }
            set { SetPropertyValue<int>(nameof(packtype), ref fpacktype, value); }
        }
        int fcomprule;
        public int comprule
        {
            get { return fcomprule; }
            set { SetPropertyValue<int>(nameof(comprule), ref fcomprule, value); }
        }
        decimal fweight;
        public decimal weight
        {
            get { return fweight; }
            set { SetPropertyValue<decimal>(nameof(weight), ref fweight, value); }
        }
        int funittype;
        public int unittype
        {
            get { return funittype; }
            set { SetPropertyValue<int>(nameof(unittype), ref funittype, value); }
        }
        decimal fbomqty;
        public decimal bomqty
        {
            get { return fbomqty; }
            set { SetPropertyValue<decimal>(nameof(bomqty), ref fbomqty, value); }
        }
        decimal fsalesqty;
        public decimal salesqty
        {
            get { return fsalesqty; }
            set { SetPropertyValue<decimal>(nameof(salesqty), ref fsalesqty, value); }
        }
        decimal ftonnes;
        public decimal tonnes
        {
            get { return ftonnes; }
            set { SetPropertyValue<decimal>(nameof(tonnes), ref ftonnes, value); }
        }
        string fmatname;
        public string matname
        {
            get { return fmatname; }
            set { SetPropertyValue<string>(nameof(matname), ref fmatname, value); }
        }
        string ftypename;
        public string typename
        {
            get { return ftypename; }
            set { SetPropertyValue<string>(nameof(typename), ref ftypename, value); }
        }
        string fpartname;
        public string partname
        {
            get { return fpartname; }
            set { SetPropertyValue<string>(nameof(partname), ref fpartname, value); }
        }
        string funitname;
        public string unitname
        {
            get { return funitname; }
            set { SetPropertyValue<string>(nameof(unitname), ref funitname, value); }
        }
    }

}
