//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class vwSamplePackWeight : XPLiteObject
    {
        int fperiod;
        public int period
        {
            get { return fperiod; }
            set { SetPropertyValue<int>(nameof(period), ref fperiod, value); }
        }
        int fsaleid;
        public int saleid
        {
            get { return fsaleid; }
            set { SetPropertyValue<int>(nameof(saleid), ref fsaleid, value); }
        }
        int fsource;
        public int source
        {
            get { return fsource; }
            set { SetPropertyValue<int>(nameof(source), ref fsource, value); }
        }
        int fdestination;
        public int destination
        {
            get { return fdestination; }
            set { SetPropertyValue<int>(nameof(destination), ref fdestination, value); }
        }
        int fmaterial;
        public int material
        {
            get { return fmaterial; }
            set { SetPropertyValue<int>(nameof(material), ref fmaterial, value); }
        }
        int fpacktype;
        public int packtype
        {
            get { return fpacktype; }
            set { SetPropertyValue<int>(nameof(packtype), ref fpacktype, value); }
        }
        int fcomprule;
        public int comprule
        {
            get { return fcomprule; }
            set { SetPropertyValue<int>(nameof(comprule), ref fcomprule, value); }
        }
        decimal fsalesqty;
        public decimal salesqty
        {
            get { return fsalesqty; }
            set { SetPropertyValue<decimal>(nameof(salesqty), ref fsalesqty, value); }
        }
        double ftonnes;
        public double tonnes
        {
            get { return ftonnes; }
            set { SetPropertyValue<double>(nameof(tonnes), ref ftonnes, value); }
        }
        int fsamplecat;
        public int samplecat
        {
            get { return fsamplecat; }
            set { SetPropertyValue<int>(nameof(samplecat), ref fsamplecat, value); }
        }
    }

}
