//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    [NonPersistent]
    public partial class vwSalesSRItems : XPLiteObject
    {
        int fcompanyoid;
        public int companyoid
        {
            get { return fcompanyoid; }
            set { SetPropertyValue<int>(nameof(companyoid), ref fcompanyoid, value); }
        }
        int fsaleperiod;
        public int saleperiod
        {
            get { return fsaleperiod; }
            set { SetPropertyValue<int>(nameof(saleperiod), ref fsaleperiod, value); }
        }
        int fproduct;
        public int product
        {
            get { return fproduct; }
            set { SetPropertyValue<int>(nameof(product), ref fproduct, value); }
        }
        int fcustomer;
        public int customer
        {
            get { return fcustomer; }
            set { SetPropertyValue<int>(nameof(customer), ref fcustomer, value); }
        }
        int fsaleid;
        public int saleid
        {
            get { return fsaleid; }
            set { SetPropertyValue<int>(nameof(saleid), ref fsaleid, value); }
        }
        int fbomitmid;
        public int bomitmid
        {
            get { return fbomitmid; }
            set { SetPropertyValue<int>(nameof(bomitmid), ref fbomitmid, value); }
        }
        int fsroid;
        public int sroid
        {
            get { return fsroid; }
            set { SetPropertyValue<int>(nameof(sroid), ref fsroid, value); }
        }
        decimal fbomitmqty;
        public decimal bomitmqty
        {
            get { return fbomitmqty; }
            set { SetPropertyValue<decimal>(nameof(bomitmqty), ref fbomitmqty, value); }
        }
        int fSource;
        public int Source
        {
            get { return fSource; }
            set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
        }
        decimal fsalesqty;
        public decimal salesqty
        {
            get { return fsalesqty; }
            set { SetPropertyValue<decimal>(nameof(salesqty), ref fsalesqty, value); }
        }
        string fCode;
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>(nameof(Code), ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fAttributeText;
        public string AttributeText
        {
            get { return fAttributeText; }
            set { SetPropertyValue<string>(nameof(AttributeText), ref fAttributeText, value); }
        }
        double fAttributeNum;
        public double AttributeNum
        {
            get { return fAttributeNum; }
            set { SetPropertyValue<double>(nameof(AttributeNum), ref fAttributeNum, value); }
        }
        int fReportType;
        public int ReportType
        {
            get { return fReportType; }
            set { SetPropertyValue<int>(nameof(ReportType), ref fReportType, value); }
        }
        int fAttributeName;
        public int AttributeName
        {
            get { return fAttributeName; }
            set { SetPropertyValue<int>(nameof(AttributeName), ref fAttributeName, value); }
        }
        double fcalcqty;
        public double calcqty
        {
            get { return fcalcqty; }
            set { SetPropertyValue<double>(nameof(calcqty), ref fcalcqty, value); }
        }
    }

}
