//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace GRPS_BLAZOR.Module.BusinessObjects.GRIPS_DBCode.GRIPS_schema
{

    //[NonPersistent]
    //public partial class vwSalesPackWeight : XPLiteObject
    //{
    //    int fcompanyoid;
    //    public int companyoid
    //    {
    //        get { return fcompanyoid; }
    //        set { SetPropertyValue<int>(nameof(companyoid), ref fcompanyoid, value); }
    //    }
    //    int fperiod;
    //    public int period
    //    {
    //        get { return fperiod; }
    //        set { SetPropertyValue<int>(nameof(period), ref fperiod, value); }
    //    }
    //    int fsaleid;
    //    public int saleid
    //    {
    //        get { return fsaleid; }
    //        set { SetPropertyValue<int>(nameof(saleid), ref fsaleid, value); }
    //    }
    //    int fProduct;
    //    public int Product
    //    {
    //        get { return fProduct; }
    //        set { SetPropertyValue<int>(nameof(Product), ref fProduct, value); }
    //    }
    //    int fCustomer;
    //    public int Customer
    //    {
    //        get { return fCustomer; }
    //        set { SetPropertyValue<int>(nameof(Customer), ref fCustomer, value); }
    //    }
    //    int fbomitmid;
    //    public int bomitmid
    //    {
    //        get { return fbomitmid; }
    //        set { SetPropertyValue<int>(nameof(bomitmid), ref fbomitmid, value); }
    //    }
    //    int fpartid;
    //    public int partid
    //    {
    //        get { return fpartid; }
    //        set { SetPropertyValue<int>(nameof(partid), ref fpartid, value); }
    //    }
    //    int fweightid;
    //    public int weightid
    //    {
    //        get { return fweightid; }
    //        set { SetPropertyValue<int>(nameof(weightid), ref fweightid, value); }
    //    }
    //    int fSource;
    //    public int Source
    //    {
    //        get { return fSource; }
    //        set { SetPropertyValue<int>(nameof(Source), ref fSource, value); }
    //    }
    //    int fdestination;
    //    public int destination
    //    {
    //        get { return fdestination; }
    //        set { SetPropertyValue<int>(nameof(destination), ref fdestination, value); }
    //    }
    //    int fMaterial;
    //    public int Material
    //    {
    //        get { return fMaterial; }
    //        set { SetPropertyValue<int>(nameof(Material), ref fMaterial, value); }
    //    }
    //    int fMaterialCategory;
    //    public int MaterialCategory
    //    {
    //        get { return fMaterialCategory; }
    //        set { SetPropertyValue<int>(nameof(MaterialCategory), ref fMaterialCategory, value); }
    //    }
    //    int fpacktype;
    //    public int packtype
    //    {
    //        get { return fpacktype; }
    //        set { SetPropertyValue<int>(nameof(packtype), ref fpacktype, value); }
    //    }
    //    int fparttype;
    //    public int parttype
    //    {
    //        get { return fparttype; }
    //        set { SetPropertyValue<int>(nameof(parttype), ref fparttype, value); }
    //    }
    //    int fcomprule;
    //    public int comprule
    //    {
    //        get { return fcomprule; }
    //        set { SetPropertyValue<int>(nameof(comprule), ref fcomprule, value); }
    //    }
    //    decimal fweight;
    //    public decimal weight
    //    {
    //        get { return fweight; }
    //        set { SetPropertyValue<decimal>(nameof(weight), ref fweight, value); }
    //    }
    //    int funittype;
    //    public int unittype
    //    {
    //        get { return funittype; }
    //        set { SetPropertyValue<int>(nameof(unittype), ref funittype, value); }
    //    }
    //    decimal fbomqty;
    //    public decimal bomqty
    //    {
    //        get { return fbomqty; }
    //        set { SetPropertyValue<decimal>(nameof(bomqty), ref fbomqty, value); }
    //    }
    //    decimal fsalesqty;
    //    public decimal salesqty
    //    {
    //        get { return fsalesqty; }
    //        set { SetPropertyValue<decimal>(nameof(salesqty), ref fsalesqty, value); }
    //    }
    //    decimal ftonnes;
    //    public decimal tonnes
    //    {
    //        get { return ftonnes; }
    //        set { SetPropertyValue<decimal>(nameof(tonnes), ref ftonnes, value); }
    //    }
    //    double frecycledtonnes;
    //    public double recycledtonnes
    //    {
    //        get { return frecycledtonnes; }
    //        set { SetPropertyValue<double>(nameof(recycledtonnes), ref frecycledtonnes, value); }
    //    }
    //    int fsamplecat;
    //    public int samplecat
    //    {
    //        get { return fsamplecat; }
    //        set { SetPropertyValue<int>(nameof(samplecat), ref fsamplecat, value); }
    //    }
    //    int fsrattrname;
    //    public int srattrname
    //    {
    //        get { return fsrattrname; }
    //        set { SetPropertyValue<int>(nameof(srattrname), ref fsrattrname, value); }
    //    }
    //    int fsrreporttype;
    //    public int srreporttype
    //    {
    //        get { return fsrreporttype; }
    //        set { SetPropertyValue<int>(nameof(srreporttype), ref fsrreporttype, value); }
    //    }
    //    int fsrcompany;
    //    public int srcompany
    //    {
    //        get { return fsrcompany; }
    //        set { SetPropertyValue<int>(nameof(srcompany), ref fsrcompany, value); }
    //    }
    //}

    public partial class vwSalesPackWeight : XPLiteObject
    {
        int frn;
        [Key(false)]
        public int rn
        {
            get => frn;
            set => SetPropertyValue<int>(nameof(rn), ref frn, value);
        }

        Company fcompanyoid;
        public Company companyoid
        {
            get { return fcompanyoid; }
            set { SetPropertyValue<Company>(nameof(companyoid), ref fcompanyoid, value); }
        }
        Period fperiod;
        public Period period
        {
            get { return fperiod; }
            set { SetPropertyValue<Period>(nameof(period), ref fperiod, value); }
        }
        SalesVolume fsaleid;
        public SalesVolume saleid
        {
            get { return fsaleid; }
            set { SetPropertyValue<SalesVolume>(nameof(saleid), ref fsaleid, value); }
        }
        Product fProduct;
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        Customer fCustomer;
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        BOMItem fbomitmid;
        public BOMItem bomitmid
        {
            get { return fbomitmid; }
            set { SetPropertyValue<BOMItem>(nameof(bomitmid), ref fbomitmid, value); }
        }
        Part fpartid;
        public Part partid
        {
            get { return fpartid; }
            set { SetPropertyValue<Part>(nameof(partid), ref fpartid, value); }
        }
        PackWeight fweightid;
        public PackWeight weightid
        {
            get { return fweightid; }
            set { SetPropertyValue<PackWeight>(nameof(weightid), ref fweightid, value); }
        }
        EnumInstance fSource;
        public EnumInstance Source
        {
            get { return fSource; }
            set { SetPropertyValue<EnumInstance>(nameof(Source), ref fSource, value); }
        }
        EnumInstance fdestination;
        public EnumInstance destination
        {
            get { return fdestination; }
            set { SetPropertyValue<EnumInstance>(nameof(destination), ref fdestination, value); }
        }
        EnumInstance fMaterial;
        public EnumInstance Material
        {
            get { return fMaterial; }
            set { SetPropertyValue<EnumInstance>(nameof(Material), ref fMaterial, value); }
        }
        EnumInstance fMaterialCategory;
        public EnumInstance MaterialCategory
        {
            get { return fMaterialCategory; }
            set { SetPropertyValue<EnumInstance>(nameof(MaterialCategory), ref fMaterialCategory, value); }
        }
        EnumInstance fpacktype;
        public EnumInstance packtype
        {
            get { return fpacktype; }
            set { SetPropertyValue<EnumInstance>(nameof(packtype), ref fpacktype, value); }
        }
        EnumInstance fparttype;
        public EnumInstance parttype
        {
            get { return fparttype; }
            set { SetPropertyValue<EnumInstance>(nameof(parttype), ref fparttype, value); }
        }
        ComplianceRule fcomprule;
        public ComplianceRule comprule
        {
            get { return fcomprule; }
            set { SetPropertyValue<ComplianceRule>(nameof(comprule), ref fcomprule, value); }
        }
        decimal fweight;
        public decimal weight
        {
            get { return fweight; }
            set { SetPropertyValue<decimal>(nameof(weight), ref fweight, value); }
        }
        EnumInstance funittype;
        public EnumInstance unittype
        {
            get { return funittype; }
            set { SetPropertyValue<EnumInstance>(nameof(unittype), ref funittype, value); }
        }
        decimal fbomqty;
        public decimal bomqty
        {
            get { return fbomqty; }
            set { SetPropertyValue<decimal>(nameof(bomqty), ref fbomqty, value); }
        }
        decimal fsalesqty;
        public decimal salesqty
        {
            get { return fsalesqty; }
            set { SetPropertyValue<decimal>(nameof(salesqty), ref fsalesqty, value); }
        }
        decimal ftonnes;
        public decimal tonnes
        {
            get { return ftonnes; }
            set { SetPropertyValue<decimal>(nameof(tonnes), ref ftonnes, value); }
        }
        double frecycledtonnes;
        public double recycledtonnes
        {
            get { return frecycledtonnes; }
            set { SetPropertyValue<double>(nameof(recycledtonnes), ref frecycledtonnes, value); }
        }
        SampleCategory fsamplecat;
        public SampleCategory samplecat
        {
            get { return fsamplecat; }
            set { SetPropertyValue<SampleCategory>(nameof(samplecat), ref fsamplecat, value); }
        }
        EnumInstance fsrattrname;
        public EnumInstance srattrname
        {
            get { return fsrattrname; }
            set { SetPropertyValue<EnumInstance>(nameof(srattrname), ref fsrattrname, value); }
        }
        EnumInstance fsrreporttype;
        public EnumInstance srreporttype
        {
            get { return fsrreporttype; }
            set { SetPropertyValue<EnumInstance>(nameof(srreporttype), ref fsrreporttype, value); }
        }
        Company fsrcompany;
        public Company srcompany
        {
            get { return fsrcompany; }
            set { SetPropertyValue<Company>(nameof(srcompany), ref fsrcompany, value); }
        }
    }

}
